import docker
import os
import socket
from dotenv import load_dotenv

def is_port_in_use(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(("127.0.0.1", port)) == 0

def start_container():
    client = docker.from_env()
    project_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    env_path = os.path.join(project_dir, "mlflow.env")

    load_dotenv(env_path)

    container_name = "mlflow_global_server"
    image_name = "mlflow_global_setup:latest"

    # Read external volume path
    host_data_dir = os.getenv("MLFLOW_DATA_DIR")
    if not host_data_dir:
        print("MLFLOW_DATA_DIR not set in mlflow.env")
        return

    host_data_dir = os.path.expanduser(host_data_dir)
    os.makedirs(host_data_dir, exist_ok=True)

    # Port configuration
    try:
        host_port = int(os.getenv("MLFLOW_PORT", "5000"))
    except ValueError:
        host_port = 5000

    if is_port_in_use(host_port):
        print(f"Port {host_port} is already in use. Change MLFLOW_PORT in mlflow.env.")
        return

    # Stop existing container
    try:
        old = client.containers.get(container_name)
        print("Stopping existing container...")
        old.stop()
        old.remove()
    except docker.errors.NotFound:
        pass

    print(f"Starting MLflow container on port {host_port}...")
    print(f"Mounting host data directory: {host_data_dir}")

    container = client.containers.run(
        image=image_name,
        name=container_name,
        environment={
            "MLFLOW_BACKEND_STORE_URI": os.getenv("MLFLOW_BACKEND_STORE_URI"),
            "MLFLOW_DEFAULT_ARTIFACT_ROOT": os.getenv("MLFLOW_DEFAULT_ARTIFACT_ROOT"),
            "MLFLOW_TRACKING_URI": os.getenv("MLFLOW_TRACKING_URI"),
        },
        ports={f"5000/tcp": host_port},
        volumes={host_data_dir: {"bind": "/mlflow_data", "mode": "rw"}},
        detach=True,
        restart_policy={"Name": "always"},
    )

    print(f"MLflow running at http://localhost:{host_port} (container: {container.name})")
    print(f"   All data mapped to: {host_data_dir}")

    # Create sourceable shell script for environment setup
    env_script_path = os.path.join(project_dir, "mlflow_env.sh")
    tracking_uri = f"http://localhost:{host_port}"
    with open(env_script_path, "w") as f:
        f.write("#!/bin/bash\n")
        f.write(f"# Generated by run_container.py - Source this file to configure MLflow CLI\n")
        f.write(f"export MLFLOW_TRACKING_URI={tracking_uri}\n")

    print(f"\n To use MLflow CLI with this server, run:")
    print(f"   source mlflow_env.sh")

if __name__ == "__main__":
    start_container()
